currency:
  url: ${CB_URL:https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml}


log4j:
  logger:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/demodb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
